from functions import *
import time
import pytest


@pytest.mark.uat
@pytest.mark.stage
def test_pp_3(driver):
    id = read(A)
    driver.get(f'{PpUrl}request/{id}/step/3')
    time.sleep(2)
    login = driver.find_element_by_xpath(simple_tag)
    login.send_keys(pp_login)
    password = driver.find_element_by_xpath(simple_tag)
    password.send_keys(pp_password)
    login_button = driver.find_element_by_xpath(simple_tag)
    login_button.click()
    time.sleep(20)
    driver.find_element_by_xpath(simple_tag).click()
    time.sleep(1)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    time.sleep(1)
    driver.find_element_by_xpath(simple_tag).click()
    time.sleep(1)
    driver.find_element_by_xpath(simple_tag).click()
    time.sleep(1)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    time.sleep(1)
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    driver.find_element_by_xpath(simple_tag).click()
    time.sleep(0.5)
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).send_keys()
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    time.sleep(2)
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).send_keys(
        random_string()
    )
    time.sleep(2)
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath(simple_tag).send_keys(simple_date)
    time.sleep(6)
    driver.find_element_by_xpath(simple_tag).click()
    driver.find_element_by_xpath().click()
    time.sleep(2)
    driver.find_element_by_xpath().click()
    time.sleep(5)
